using CodeGeneration;

namespace Tests;

public class ParsingFlowTests
{
    private const string SourceCsv =
        """
        Ability,Id,Cooldown,Damage,AoERadius,AoEDamage
        Melee,melee,1.0s,5.0,0.0,0.0
        Ranged,ranged,1.5s,5.0,0.0,0.0
        Fireball,fireball,3.0s,10.0,7.0,5.0
        """;
    
    private const string Expected = 
        """
        /*
            Note: This file has been autogenerated from ''. Do not edit it directly.
        */
        #nullable enable
        
        using CodeGeneration;
        
        namespace CsvData;
        
        using System.Collections.Generic;
        
        public static class StaticName
        {
            public class Ability
            {
                public IdString Id { get; init; } = new IdString(string.Empty);
                public TimeSpan Cooldown { get; init; } = TimeSpan.Zero;
                public float Damage { get; init; }
                public float AoERadius { get; init; }
                public float AoEDamage { get; init; }
            }
        
            public static readonly Ability Melee = new()
            {
                Id = new IdString("melee"),
                Cooldown = TimeSpan.FromSeconds(1.0),
                Damage = 5.0f,
                AoERadius = 0.0f,
                AoEDamage = 0.0f,
            };
        
            public static readonly Ability Ranged = new()
            {
                Id = new IdString("ranged"),
                Cooldown = TimeSpan.FromSeconds(1.5),
                Damage = 5.0f,
                AoERadius = 0.0f,
                AoEDamage = 0.0f,
            };
        
            public static readonly Ability Fireball = new()
            {
                Id = new IdString("fireball"),
                Cooldown = TimeSpan.FromSeconds(3.0),
                Damage = 10.0f,
                AoERadius = 7.0f,
                AoEDamage = 5.0f,
            };
        
            public static readonly IReadOnlyCollection<Ability> All = new[]
            {
                Melee,
                Ranged,
                Fireball,
            };
        }
        """;
    
    [Test]
    public void VerifyResultingSourceCode()
    {
        var csvReader = new CsvReader();
        var csv = csvReader.ReadCsv(SourceCsv);

        var parser = new CsvParser();
        var document = parser.ParseCsv(csv);

        var template = new CsvTemplate
        {
            StaticClassName = "StaticName",
            CsvDocument = document
        };
        
        var templateText = template.TransformText();
        
        Assert.That(templateText, Is.EqualTo(Expected));
    }
}